//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.ScrumStatus {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.ScrumStatus.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   スクラムの追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddNewScrumButtonText {
            get {
                return ResourceManager.GetString("AddNewScrumButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャネル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddToChannelTitle {
            get {
                return ResourceManager.GetString("AddToChannelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Botが失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BotFailureTitle {
            get {
                return ResourceManager.GetString("BotFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャネルを選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelNameValidationText {
            get {
                return ResourceManager.GetString("ChannelNameValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同じ名前のスクラムが既にチャネルに設定されています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DuplicateScrumValidationText {
            get {
                return ResourceManager.GetString("DuplicateScrumValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクラム終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EndScrumButtonText {
            get {
                return ResourceManager.GetString("EndScrumButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問題が発生し動作の実行ができません。数分後に再試行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクラムメンバーがいません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorNoScrumMembersPresent {
            get {
                return ResourceManager.GetString("ErrorNoScrumMembersPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存時に問題が発生しました。数分後に再試行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorSavingScrumData {
            get {
                return ResourceManager.GetString("ErrorSavingScrumData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}, このスクラムはすでに削除されたか、非アクティブに設定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorScrumConfigurationDetailsNullOrInactive {
            get {
                return ResourceManager.GetString("ErrorScrumConfigurationDetailsNullOrInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} スクラムはすでに削除されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorScrumDeleted {
            get {
                return ResourceManager.GetString("ErrorScrumDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} このスクラムは削除されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorScrumDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorScrumDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}, スクラムメンバーのみが実行できる動作です。メンバーへの追加を依頼してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorUserIsNotPartOfRunningScrumAndTryToEndScrum {
            get {
                return ResourceManager.GetString("ErrorUserIsNotPartOfRunningScrumAndTryToEndScrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}, スクラムメンバーのみが実行できる動作です。メンバーへの追加を依頼してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorUserIsNotPartOfRunningScrumAndTryUpdateStatus {
            get {
                return ResourceManager.GetString("ErrorUserIsNotPartOfRunningScrumAndTryUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一般 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralChannel {
            get {
                return ResourceManager.GetString("GeneralChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お困りですか？コマンドを選択または入力してください： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpCardTitleText {
            get {
                return ResourceManager.GetString("HelpCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクラム メンバー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MembersListTitle {
            get {
                return ResourceManager.GetString("MembersListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果が見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoMatchesFoundText {
            get {
                return ResourceManager.GetString("NoMatchesFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解決が必要な相談事項があれば共有してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScrumDetailsAnyBlockersTitle {
            get {
                return ResourceManager.GetString("ScrumDetailsAnyBlockersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクラムの詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScrumDetailsButtonText {
            get {
                return ResourceManager.GetString("ScrumDetailsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータス: {0} / {1} 完了済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScrumDetailsRespondedVsTotalUserStatus {
            get {
                return ResourceManager.GetString("ScrumDetailsRespondedVsTotalUserStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクラムの詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScrumDetailsTitle {
            get {
                return ResourceManager.GetString("ScrumDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次回までの達成目標を共有してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScrumDetailsTodayTaskDescriptionTitle {
            get {
                return ResourceManager.GetString("ScrumDetailsTodayTaskDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   （問題を抱えています！） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScrumDetailsUserIsBlocked {
            get {
                return ResourceManager.GetString("ScrumDetailsUserIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在までの進行状況を共有してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScrumDetailsYesterdayTaskDescriptionTitle {
            get {
                return ResourceManager.GetString("ScrumDetailsYesterdayTaskDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScrumEnableButtonTitle {
            get {
                return ResourceManager.GetString("ScrumEnableButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクティブ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScrumRunningStatusActive {
            get {
                return ResourceManager.GetString("ScrumRunningStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScrumRunningStatusClosed {
            get {
                return ResourceManager.GetString("ScrumRunningStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScrumStatusCompletedForUser {
            get {
                return ResourceManager.GetString("ScrumStatusCompletedForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScrumStatusNotStarted {
            get {
                return ResourceManager.GetString("ScrumStatusNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャネルの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectChannelPlaceholder {
            get {
                return ResourceManager.GetString("SelectChannelPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間の選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectTimePlaceholder {
            get {
                return ResourceManager.GetString("SelectTimePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイムゾーンの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectTimeZonePlaceholder {
            get {
                return ResourceManager.GetString("SelectTimeZonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーの選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectUserPlaceholder {
            get {
                return ResourceManager.GetString("SelectUserPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsButtonText {
            get {
                return ResourceManager.GetString("SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定に移動し新しいスクラムを作成または既存のスクラムを編集する： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsCardTitleText {
            get {
                return ResourceManager.GetString("SettingsCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   毎日の開始時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartEveryDayTitle {
            get {
                return ResourceManager.GetString("StartEveryDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}人のユーザーが問題を抱えています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartScrumCardBlockedText {
            get {
                return ResourceManager.GetString("StartScrumCardBlockedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   こんにちは！スクラムが開始されました。入力を行いましょう。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartScrumCardWelcomeText {
            get {
                return ResourceManager.GetString("StartScrumCardWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始時間を選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartTimeValidationText {
            get {
                return ResourceManager.GetString("StartTimeValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   おつかれさまでした！このスクラムは完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SuccessMessageAfterEndingScrum {
            get {
                return ResourceManager.GetString("SuccessMessageAfterEndingScrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タスクモジュールのフェッチで無効なコマンドが検出されました。コマンド：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaskModuleInvalidCommandText {
            get {
                return ResourceManager.GetString("TaskModuleInvalidCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メンバーは2人以上選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TeamMembersValidationText {
            get {
                return ResourceManager.GetString("TeamMembersValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チーム名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TeamNameTitle {
            get {
                return ResourceManager.GetString("TeamNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チーム名は空欄にできません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TeamNameValidationText {
            get {
                return ResourceManager.GetString("TeamNameValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイムゾーン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeZoneTitle {
            get {
                return ResourceManager.GetString("TimeZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイムゾーンを選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeZoneValidationText {
            get {
                return ResourceManager.GetString("TimeZoneValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内容を入力してください（最大300字） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateStatusAnyBlockersPlaceholder {
            get {
                return ResourceManager.GetString("UpdateStatusAnyBlockersPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解決が必要な相談事項があれば共有してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateStatusAnyBlockersTitle {
            get {
                return ResourceManager.GetString("UpdateStatusAnyBlockersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータスの更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateStatusButtonText {
            get {
                return ResourceManager.GetString("UpdateStatusButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateStatusSubmitButtonText {
            get {
                return ResourceManager.GetString("UpdateStatusSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータスの更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateStatusTitle {
            get {
                return ResourceManager.GetString("UpdateStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このフィールドは空欄にできません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateStatusTodayDescriptionErrorMessage {
            get {
                return ResourceManager.GetString("UpdateStatusTodayDescriptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内容を入力してください（最大300字） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateStatusTodayDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("UpdateStatusTodayDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次回までの達成目標を共有してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateStatusTodayDescriptionTitle {
            get {
                return ResourceManager.GetString("UpdateStatusTodayDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このフィールドは空欄にできません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateStatusYesterdayDescriptionErrorMessage {
            get {
                return ResourceManager.GetString("UpdateStatusYesterdayDescriptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内容を入力してください（最大300字） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateStatusYesterdayDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("UpdateStatusYesterdayDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在までの進行状況を共有してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateStatusYesterdayDescriptionTitle {
            get {
                return ResourceManager.GetString("UpdateStatusYesterdayDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクラムが完了したらスクラム終了を選択してください。スクラムを終了すると誰も内容を更新することはできなくなります。内容を更新したい場合は新しいスクラムを開始してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardEndScrumTextDesc {
            get {
                return ResourceManager.GetString("WelcomeCardEndScrumTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **スクラム終了** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardEndScrumTextHeading {
            get {
                return ResourceManager.GetString("WelcomeCardEndScrumTextHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardSettingsButtonText {
            get {
                return ResourceManager.GetString("WelcomeCardSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクラムが開始されるとユーザーが現在のステータスを入力するフォームが作成されます。更新内容はチャネル内のすべてのユーザーが確認可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardStartScrumTextDesc {
            get {
                return ResourceManager.GetString("WelcomeCardStartScrumTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **スクラム開始** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardStartScrumTextHeading {
            get {
                return ResourceManager.GetString("WelcomeCardStartScrumTextHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリでチームのステータスや更新情報を確認可能です。チャネル内のすべてのメンバーが利用できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardSubtitleText {
            get {
                return ResourceManager.GetString("WelcomeCardSubtitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ようこそ！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクラムを開始しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeCardWantToStartScrumText {
            get {
                return ResourceManager.GetString("WelcomeCardWantToStartScrumText", resourceCulture);
            }
        }
    }
}
